#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Dec 13, 2017 10:07:43 PM
import sys
import numpy as np
import tkinter.messagebox as fmsgbox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import equation_solver_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.resizable(False, False)
    top = Equation_solver (root)
    equation_solver_support.init(root, top)
    root.mainloop()

w = None
def create_Equation_solver (root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Equation_solver (w)
    equation_solver_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Equation_solver ():
    global w
    w.destroy()
    w = None


class Equation_solver:
    def doRefresh(self):
        self.Entry1.delete(0, END)
        self.Entry2.delete(0, END)
        self.Entry3.delete(0, END)
        self.Entry4.delete(0, END)
        self.Entry5.delete(0, END)
        self.Entry6.delete(0, END)
        self.Entry7.delete(0, END)
        self.Entry8.delete(0, END)
        self.Entry9.delete(0, END)
        self.Entry10.delete(0, END)
        self.Entry11.delete(0, END)
        self.Entry12.delete(0, END)
        self.Entry13.delete(0, END)
        self.Entry14.delete(0, END)
        self.Entry15.delete(0, END)
        return

    def solveMatrix(self):
        condition1 = ((self.Entry1.get() is "") or (self.Entry2.get() is "") or (self.Entry3.get() is "") or
                      (self.Entry4.get() is "") or (self.Entry5.get() is "") or (self.Entry6.get() is "") or
                      (self.Entry7.get() is "") or (self.Entry8.get() is "") or (self.Entry9.get() is "") or
                      (self.Entry10.get() is "") or (self.Entry11.get() is "") or (self.Entry12.get() is ""))
        if (condition1 is True):
            #self.Label6.configure(text="Invalid user input. Please check.")
            fmsgbox.showinfo("Solver", "Invalid user input. Please check")
            return
        matrix1 = np.array([[float(self.Entry1.get()),float(self.Entry2.get()),float(self.Entry3.get())],
                            [float(self.Entry5.get()),float(self.Entry6.get()),float(self.Entry7.get())],
                            [float(self.Entry9.get()),float(self.Entry10.get()),float(self.Entry11.get())]])
                            


        matrix2 = np.linalg.inv(matrix1)
        matrix3 = np.array([float(self.Entry4.get()), float(self.Entry8.get()), float(self.Entry12.get())])
        results = np.round(matrix2.dot(matrix3),decimals=10)
        self.Entry13.insert(0,results[0])
        self.Entry14.insert(0,results[1])
        self.Entry15.insert(0,results[2])
        return

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x475+664+83")
        top.title("Equation solver (3x3)")
        top.configure(background="#d9d9d9")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.06, rely=0.29, height=26, width=92)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(justify=LEFT)
        self.Label1.configure(text='''Equation 2''')
        self.Label1.configure(width=92)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.06, rely=0.47, height=26, width=92)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(justify=LEFT)
        self.Label2.configure(text='''Equation 3''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.06, rely=0.1, height=26, width=92)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(justify=LEFT)
        self.Label3.configure(text='''Equation 1''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.08, rely=0.19, relheight=0.05, relwidth=0.11)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=64)

        self.Label4 = Label(top)
        self.Label4.place(relx=0.2, rely=0.19, height=26, width=35)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''X    +''')
        self.Label4.configure(width=35)

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.28, rely=0.19, relheight=0.05, relwidth=0.11)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=64)

        self.Label5 = Label(top)
        self.Label5.place(relx=0.4, rely=0.19, height=26, width=35)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Y    +''')

        self.Entry3 = Entry(top)
        self.Entry3.place(relx=0.48, rely=0.19, relheight=0.05, relwidth=0.11)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(width=64)

        self.Label6 = Label(top)
        self.Label6.place(relx=0.6, rely=0.19, height=26, width=41)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Z    =''')
        self.Label6.configure(width=61)

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Entry4 = Entry(top)
        self.Entry4.place(relx=0.72, rely=0.19, relheight=0.05, relwidth=0.11)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(width=64)

        self.Entry5 = Entry(top)
        self.Entry5.place(relx=0.08, rely=0.38, relheight=0.05, relwidth=0.11)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(width=64)

        self.Entry6 = Entry(top)
        self.Entry6.place(relx=0.28, rely=0.38, relheight=0.05, relwidth=0.11)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(width=64)

        self.Entry7 = Entry(top)
        self.Entry7.place(relx=0.48, rely=0.38, relheight=0.05, relwidth=0.11)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(width=64)

        self.Entry8 = Entry(top)
        self.Entry8.place(relx=0.72, rely=0.38, relheight=0.05, relwidth=0.11)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(width=64)

        self.Entry9 = Entry(top)
        self.Entry9.place(relx=0.08, rely=0.57, relheight=0.05, relwidth=0.11)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(width=64)

        self.Entry10 = Entry(top)
        self.Entry10.place(relx=0.28, rely=0.57, relheight=0.05, relwidth=0.11)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(width=64)

        self.Entry11 = Entry(top)
        self.Entry11.place(relx=0.48, rely=0.57, relheight=0.05, relwidth=0.11)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(width=64)

        self.Entry12 = Entry(top)
        self.Entry12.place(relx=0.72, rely=0.57, relheight=0.05, relwidth=0.11)
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(insertbackground="black")
        self.Entry12.configure(width=64)

        self.Label7 = Label(top)
        self.Label7.place(relx=0.2, rely=0.38, height=26, width=41)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''X    +''')

        self.Label8 = Label(top)
        self.Label8.place(relx=0.2, rely=0.57, height=26, width=41)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''X    +''')

        self.Label9 = Label(top)
        self.Label9.place(relx=0.4, rely=0.38, height=26, width=40)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Y    +''')

        self.Label10 = Label(top)
        self.Label10.place(relx=0.4, rely=0.57, height=26, width=40)
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''Y    +''')

        self.Label11 = Label(top)
        self.Label11.place(relx=0.6, rely=0.38, height=26, width=41)
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''Z    =''')

        self.Label12 = Label(top)
        self.Label12.place(relx=0.6, rely=0.57, height=26, width=41)
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''Z    =''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.08, rely=0.67, height=33, width=48)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Solve''', command=self.solveMatrix)

        self.Label13 = Label(top)
        self.Label13.place(relx=0.08, rely=0.81, height=26, width=52)
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''Results''')

        self.Entry13 = Entry(top)
        self.Entry13.place(relx=0.28, rely=0.81, relheight=0.05, relwidth=0.11)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(width=64)

        self.Entry14 = Entry(top)
        self.Entry14.place(relx=0.48, rely=0.81, relheight=0.05, relwidth=0.11)
        self.Entry14.configure(background="white")
        self.Entry14.configure(disabledforeground="#a3a3a3")
        self.Entry14.configure(font="TkFixedFont")
        self.Entry14.configure(foreground="#000000")
        self.Entry14.configure(insertbackground="black")
        self.Entry14.configure(width=64)

        self.Entry15 = Entry(top)
        self.Entry15.place(relx=0.68, rely=0.81, relheight=0.05, relwidth=0.11)
        self.Entry15.configure(background="white")
        self.Entry15.configure(disabledforeground="#a3a3a3")
        self.Entry15.configure(font="TkFixedFont")
        self.Entry15.configure(foreground="#000000")
        self.Entry15.configure(insertbackground="black")
        self.Entry15.configure(width=64)

        self.Label14 = Label(top)
        self.Label14.place(relx=0.22, rely=0.81, height=26, width=33)
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(text='''X  =''')

        self.Label15 = Label(top)
        self.Label15.place(relx=0.42, rely=0.81, height=26, width=32)
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(text='''Y  =''')

        self.Label16 = Label(top)
        self.Label16.place(relx=0.62, rely=0.81, height=26, width=33)
        self.Label16.configure(background="#d9d9d9")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(text='''Z  =''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.22, rely=0.67, height=33, width=56)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Refresh''', command=self.doRefresh)






if __name__ == '__main__':
    vp_start_gui()



